Creating ssh keys for the deploy andrewforward

diff --git a/install b/install
--- a/install
+++ b/install
@@ -12,6 +12,7 @@ DEPLOYKEYS_KEYNAME=${DEPLOYKEYS_KEYNAME-id_dsa}
 DEPLOYKEYS_KNOWN_HOSTS=${DEPLOYKEYS_KNOWN_HOSTS-known_hosts}
 DEPLOYKEYS_ADD_GITHUB=${DEPLOYKEYS_ADD_GITHUB-false}
 DEPLOYKEYS_ADD_BITBUCKET=${DEPLOYKEYS_ADD_BITBUCKET-false}
+SSHKEYS=${SSHKEYS=false}
 
 #-----------
 # Install Script
@@ -23,6 +24,18 @@ if [[ "$LOGLEVEL" -le "$DEBUG_LEVEL" ]]; then
   DEPLOYKEYS_OUTPUT=/tmp/deploykeys_install.log
 else
   DEPLOYKEYS_OUTPUT=/dev/null
+fi
+
+if [[ "$SSHKEYS" == true ]] && [[ ! -e ${HOME}/.ssh/id_dsa ]]; then
+  notify "  -- Creating ssh keys ${HOME}/.ssh/id_dsa"
+  mkdir -p ${HOME}/.ssh
+  SCRIPT_OUTPUT=$(ssh-keygen -t dsa -N "" -f ${HOME}/.ssh/id_dsa > $DEPLOYKEYS_OUTPUT 2>&1)
+  ERROR="Unable create ssh keys for $USER ..." ./bits/bootstrap/failonerrors $? $DEPLOYKEYS_OUTPUT
+  [ $? -ne 0 ] && exit 1
+elif [[ "$SSHKEYS" != true ]]; then
+  warn "  -- Ignoring SSH keys check for $USER, set SSHKEYS=true if you want to check for and create SSH keys."
+else
+  debug "  -- SSH keys already setup for $USER (${HOME}/.ssh/id_dsa)"
 fi
 
 if [[ "`which expect 2> /dev/null`" == "" ]]; then
